/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as InterviewsIndexRouteImport } from './routes/interviews.index'
import { Route as InterviewsSlugRouteImport } from './routes/interviews.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIndexRoute = InterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsSlugRoute = InterviewsSlugRouteImport.update({
  id: '/interviews/$slug',
  path: '/interviews/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/instagram': typeof InstagramRoute
  '/stories': typeof StoriesRoute
  '/interviews/$slug': typeof InterviewsSlugRoute
  '/interviews/': typeof InterviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/instagram': typeof InstagramRoute
  '/stories': typeof StoriesRoute
  '/interviews/$slug': typeof InterviewsSlugRoute
  '/interviews': typeof InterviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/instagram': typeof InstagramRoute
  '/stories': typeof StoriesRoute
  '/interviews/$slug': typeof InterviewsSlugRoute
  '/interviews/': typeof InterviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/instagram'
    | '/stories'
    | '/interviews/$slug'
    | '/interviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/instagram'
    | '/stories'
    | '/interviews/$slug'
    | '/interviews'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/instagram'
    | '/stories'
    | '/interviews/$slug'
    | '/interviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InstagramRoute: typeof InstagramRoute
  StoriesRoute: typeof StoriesRoute
  InterviewsSlugRoute: typeof InterviewsSlugRoute
  InterviewsIndexRoute: typeof InterviewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/': {
      id: '/interviews/'
      path: '/interviews'
      fullPath: '/interviews/'
      preLoaderRoute: typeof InterviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/$slug': {
      id: '/interviews/$slug'
      path: '/interviews/$slug'
      fullPath: '/interviews/$slug'
      preLoaderRoute: typeof InterviewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InstagramRoute: InstagramRoute,
  StoriesRoute: StoriesRoute,
  InterviewsSlugRoute: InterviewsSlugRoute,
  InterviewsIndexRoute: InterviewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
